package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFixTypedRootAliasFromSchema(t *testing.T) {
	dir := t.TempDir()
	schemaDir := filepath.Join(dir, "internal", "nfse", "schemas", "v1_0", "core")
	genDir := filepath.Join(dir, "internal", "nfse", "gen", "v1_0", "core")

	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir schema dir: %v", err)
	}
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		t.Fatalf("mkdir gen dir: %v", err)
	}

	schemaPath := filepath.Join(schemaDir, "doc.xsd")
	if err := os.WriteFile(schemaPath, []byte(`<schema><element name="Doc" type="TDoc"/></schema>`), 0o644); err != nil {
		t.Fatalf("write schema: %v", err)
	}

	generatedPath := filepath.Join(genDir, "doc.xsd.go")
	generated := strings.Join([]string{
		"// Code generated by xgen. DO NOT EDIT.",
		"",
		"package schema",
		"",
		"// Doc is the root element.",
		"type Doc string",
		"",
	}, "\n")

	updated := fixTypedRootAliasFromSchema(generatedPath, generated)
	if !strings.Contains(updated, "type Doc *TDoc") {
		t.Fatalf("expected typed root alias rewrite, got:\n%s", updated)
	}
}

func TestSchemaPathForGenerated(t *testing.T) {
	dir := t.TempDir()
	schemaDir := filepath.Join(dir, "internal", "nfe", "schemas", "v4_0", "consulta_situacao")
	genPath := filepath.Join(dir, "internal", "nfe", "gen", "v4_0", "consulta_situacao", "cons.xsd.go")

	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir schema dir: %v", err)
	}
	schemaPath := filepath.Join(schemaDir, "cons.xsd")
	if err := os.WriteFile(schemaPath, []byte("<schema/>"), 0o644); err != nil {
		t.Fatalf("write schema: %v", err)
	}

	got, ok := schemaPathForGenerated(genPath)
	if !ok {
		t.Fatal("expected schemaPathForGenerated to resolve schema path")
	}
	if got != schemaPath {
		t.Fatalf("expected schema path %q, got %q", schemaPath, got)
	}
}

func TestReplaceTypedCTeEventPayloads(t *testing.T) {
	input := `package schema

import (
	"encoding/xml"
)

type TAnonComplexInfModal1 struct {
	XMLName         xml.Name ` + "`xml:\"infModal\"`" + `
	VersaoModalAttr string   ` + "`xml:\"versaoModal,attr\"`" + `
}

type TAnonComplexInfModal2 struct {
	XMLName         xml.Name ` + "`xml:\"infModal\"`" + `
	VersaoModalAttr string   ` + "`xml:\"versaoModal,attr\"`" + `
}

type TAnonComplexInfModal3 struct {
	XMLName         xml.Name ` + "`xml:\"infModal\"`" + `
	VersaoModalAttr string   ` + "`xml:\"versaoModal,attr\"`" + `
}
`

	path := filepath.Join("internal", "cte", "gen", "v4_0", "cte", "cteTiposBasico_v4.00.xsd.go")
	updated := replaceTypedCTeEventPayloads(path, input)

	wantSnippets := []string{
		`modalaereo "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_aereo"`,
		`modalrodoviario "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_rodoviario"`,
		`modalmultimodal "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_multimodal"`,
		"Rodo",
		"modalrodoviario.",
		"`xml:\"rodo,omitempty\"`",
		"Multimodal",
		"modalmultimodal.",
		"`xml:\"multimodal,omitempty\"`",
	}
	for _, snippet := range wantSnippets {
		if !strings.Contains(updated, snippet) {
			t.Fatalf("updated source missing snippet %q:\n%s", snippet, updated)
		}
	}
}
