package main

import (
	"bytes"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/awafinance/fiscal/internal/codegen/postprocess"
)

const (
	infBPeCompField      = "\tComp        *TAnonComplexComp1        `xml:\"comp\"`"
	infBPeCompFieldFixed = "\tComp        *TAnonComplexComp12       `xml:\"comp\"`"
)

var (
	rootAliasFile = regexp.MustCompile(`\A// Code generated by xgen\. DO NOT EDIT\.\n\npackage schema\n\n// [^\n]+\ntype ([A-Z][A-Za-z0-9_]*) string\n\z`)

	cteEventPayloads = map[string]string{
		"evento_cce":                    "evCCeCTe",
		"evento_cancel":                 "evCancCTe",
		"evento_ce":                     "evCECTe",
		"evento_cancel_ce":              "evCancCECTe",
		"evento_cancel_ie":              "evCancIECTe",
		"evento_cancel_prest_desacordo": "evCancPrestDesacordo",
		"evento_epec":                   "evEPECCTe",
		"evento_gtv":                    "evGTV",
		"evento_ie":                     "evIECTe",
		"evento_prest_desacordo":        "evPrestDesacordo",
		"evento_reg_multimodal":         "evRegMultimodal",
	}
)

func codegenFamilies() []family {
	return []family{
		bpeFamily(),
		cteFamily(),
		mdfeFamily(),
		nfeFamily(),
		nfseFamily(),
	}
}

func bpeFamily() family {
	return family{
		name: "bpe",
		normalizeDirs: []string{
			"internal/bpe/schemas/v1_0/core",
			"internal/bpe/schemas/v1_0/evento_cancel",
			"internal/bpe/schemas/v1_0/evento_alteracao_poltrona",
			"internal/bpe/schemas/v1_0/evento_excesso_bagagem",
			"internal/bpe/schemas/v1_0/evento_nao_emb",
		},
		xgenJobs: []xgenJob{
			{"v1_0/core", "v1_0/core"},
			{"v1_0/evento_cancel", "v1_0/evento_cancel"},
			{"v1_0/evento_alteracao_poltrona", "v1_0/evento_alteracao_poltrona"},
			{"v1_0/evento_excesso_bagagem", "v1_0/evento_excesso_bagagem"},
			{"v1_0/evento_nao_emb", "v1_0/evento_nao_emb"},
		},
		postprocess: postprocessBPe,
	}
}

func cteFamily() family {
	return family{
		name: "cte",
		normalizeDirs: []string{
			"internal/cte/schemas/v4_0/cte",
			"internal/cte/schemas/v4_0/cte_os",
			"internal/cte/schemas/v4_0/consulta_situacao",
			"internal/cte/schemas/v4_0/status_servico",
			"internal/cte/schemas/v4_0/cte_simp",
			"internal/cte/schemas/v4_0/gtve",
			"internal/cte/schemas/v4_0/modal_aereo",
			"internal/cte/schemas/v4_0/modal_aquaviario",
			"internal/cte/schemas/v4_0/modal_dutoviario",
			"internal/cte/schemas/v4_0/modal_ferroviario",
			"internal/cte/schemas/v4_0/modal_rodoviario",
			"internal/cte/schemas/v4_0/modal_rodoviario_os",
			"internal/cte/schemas/v4_0/modal_multimodal",
			"internal/cte/schemas/v4_0/evento_cce",
			"internal/cte/schemas/v4_0/evento_cancel",
			"internal/cte/schemas/v4_0/evento_ce",
			"internal/cte/schemas/v4_0/evento_cancel_ce",
			"internal/cte/schemas/v4_0/evento_cancel_ie",
			"internal/cte/schemas/v4_0/evento_cancel_prest_desacordo",
			"internal/cte/schemas/v4_0/evento_epec",
			"internal/cte/schemas/v4_0/evento_gtv",
			"internal/cte/schemas/v4_0/evento_ie",
			"internal/cte/schemas/v4_0/evento_prest_desacordo",
			"internal/cte/schemas/v4_0/evento_reg_multimodal",
			"internal/cte/schemas/v1_0/dist_dfe",
		},
		xgenJobs: []xgenJob{
			{"v1_0/dist_dfe", "v1_0/dist_dfe"},
			{"v4_0/cte", "v4_0/cte"},
			{"v4_0/cte_os", "v4_0/cte_os"},
			{"v4_0/consulta_situacao", "v4_0/consulta_situacao"},
			{"v4_0/status_servico", "v4_0/status_servico"},
			{"v4_0/cte_simp", "v4_0/cte_simp"},
			{"v4_0/gtve", "v4_0/gtve"},
			{"v4_0/modal_aereo/cteModalAereo_v4.00.xsd", "v4_0/modal_aereo/cteModalAereo_v4.00.xsd.go"},
			{"v4_0/modal_aquaviario/cteModalAquaviario_v4.00.xsd", "v4_0/modal_aquaviario/cteModalAquaviario_v4.00.xsd.go"},
			{"v4_0/modal_dutoviario/cteModalDutoviario_v4.00.xsd", "v4_0/modal_dutoviario/cteModalDutoviario_v4.00.xsd.go"},
			{"v4_0/modal_ferroviario/cteModalFerroviario_v4.00.xsd", "v4_0/modal_ferroviario/cteModalFerroviario_v4.00.xsd.go"},
			{"v4_0/modal_rodoviario/cteModalRodoviario_v4.00.xsd", "v4_0/modal_rodoviario/cteModalRodoviario_v4.00.xsd.go"},
			{"v4_0/modal_rodoviario_os/cteModalRodoviarioOS_v4.00.xsd", "v4_0/modal_rodoviario_os/cteModalRodoviarioOS_v4.00.xsd.go"},
			{"v4_0/modal_multimodal/cteMultiModal_v4.00.xsd", "v4_0/modal_multimodal/cteMultiModal_v4.00.xsd.go"},
			{"v4_0/evento_cce", "v4_0/evento_cce"},
			{"v4_0/evento_cancel", "v4_0/evento_cancel"},
			{"v4_0/evento_ce", "v4_0/evento_ce"},
			{"v4_0/evento_cancel_ce", "v4_0/evento_cancel_ce"},
			{"v4_0/evento_cancel_ie", "v4_0/evento_cancel_ie"},
			{"v4_0/evento_cancel_prest_desacordo", "v4_0/evento_cancel_prest_desacordo"},
			{"v4_0/evento_epec", "v4_0/evento_epec"},
			{"v4_0/evento_gtv", "v4_0/evento_gtv"},
			{"v4_0/evento_ie", "v4_0/evento_ie"},
			{"v4_0/evento_prest_desacordo", "v4_0/evento_prest_desacordo"},
			{"v4_0/evento_reg_multimodal", "v4_0/evento_reg_multimodal"},
		},
		postprocess: postprocessCTe,
	}
}

func mdfeFamily() family {
	return family{
		name: "mdfe",
		normalizeDirs: []string{
			"internal/mdfe/schemas/v3_0/mdfe",
			"internal/mdfe/schemas/v3_0/cons_nao_enc",
			"internal/mdfe/schemas/v3_0/cons_reci",
			"internal/mdfe/schemas/v3_0/consulta_situacao",
			"internal/mdfe/schemas/v3_0/status_servico",
			"internal/mdfe/schemas/v3_0/evento",
			"internal/mdfe/schemas/v3_0/evento_cancel",
			"internal/mdfe/schemas/v3_0/evento_enc",
			"internal/mdfe/schemas/v3_0/evento_inc_condutor",
			"internal/mdfe/schemas/v3_0/evento_inclusao_dfe",
			"internal/mdfe/schemas/v3_0/evento_pagto_oper",
			"internal/mdfe/schemas/v3_0/evento_alteracao_pagto_serv",
			"internal/mdfe/schemas/v3_0/evento_confirma_serv",
			"internal/mdfe/schemas/v3_0/dist_mdfe",
			"internal/mdfe/schemas/v3_0/consulta_dfe",
			"internal/mdfe/schemas/v1_0/dist_dfe",
		},
		xgenJobs: []xgenJob{
			{"v1_0/dist_dfe", "v1_0/dist_dfe"},
			{"v3_0/mdfe", "v3_0/mdfe"},
			{"v3_0/cons_nao_enc", "v3_0/cons_nao_enc"},
			{"v3_0/cons_reci", "v3_0/cons_reci"},
			{"v3_0/consulta_situacao", "v3_0/consulta_situacao"},
			{"v3_0/status_servico", "v3_0/status_servico"},
			{"v3_0/evento", "v3_0/evento"},
			{"v3_0/evento_cancel", "v3_0/evento_cancel"},
			{"v3_0/evento_enc", "v3_0/evento_enc"},
			{"v3_0/evento_inc_condutor", "v3_0/evento_inc_condutor"},
			{"v3_0/evento_inclusao_dfe", "v3_0/evento_inclusao_dfe"},
			{"v3_0/evento_pagto_oper", "v3_0/evento_pagto_oper"},
			{"v3_0/evento_alteracao_pagto_serv", "v3_0/evento_alteracao_pagto_serv"},
			{"v3_0/evento_confirma_serv", "v3_0/evento_confirma_serv"},
			{"v3_0/dist_mdfe", "v3_0/dist_mdfe"},
			{"v3_0/consulta_dfe", "v3_0/consulta_dfe"},
		},
		postprocess: postprocessMDFe,
	}
}

func nfeFamily() family {
	return family{
		name: "nfe",
		normalizeDirs: []string{
			"internal/nfe/schemas/v1_0/dist_dfe",
			"internal/nfe/schemas/v1_0/ator_interessado",
			"internal/nfe/schemas/v1_0/evento_entrega",
			"internal/nfe/schemas/v1_0/evento_cancel_entrega",
			"internal/nfe/schemas/v1_0/evento_cancel",
			"internal/nfe/schemas/v1_0/evento_cce",
			"internal/nfe/schemas/v1_0/evento_generico",
			"internal/nfe/schemas/v1_0/evento_mde",
			"internal/nfe/schemas/v1_0/evento_insucesso",
			"internal/nfe/schemas/v1_0/evento_cancel_insucesso",
			"internal/nfe/schemas/v1_0/epec",
			"internal/nfe/schemas/v2_0/cons",
			"internal/nfe/schemas/v4_0/nfe_proc",
			"internal/nfe/schemas/v4_0/consulta_situacao",
			"internal/nfe/schemas/v4_0/status_servico",
			"internal/nfe/schemas/v4_0/inutilizacao",
		},
		xgenJobs: []xgenJob{
			{"v1_0/ator_interessado", "v1_0/ator_interessado"},
			{"v1_0/evento_entrega", "v1_0/evento_entrega"},
			{"v1_0/evento_cancel_entrega", "v1_0/evento_cancel_entrega"},
			{"v1_0/evento_cancel", "v1_0/evento_cancel"},
			{"v1_0/evento_cce", "v1_0/evento_cce"},
			{"v1_0/evento_generico", "v1_0/evento_generico"},
			{"v1_0/evento_mde", "v1_0/evento_mde"},
			{"v1_0/evento_insucesso", "v1_0/evento_insucesso"},
			{"v1_0/evento_cancel_insucesso", "v1_0/evento_cancel_insucesso"},
			{"v1_0/epec", "v1_0/epec"},
			{"v1_0/dist_dfe", "v1_0/dist_dfe"},
			{"v2_0/cons", "v2_0/cons"},
			{"v4_0/nfe_proc", "v4_0/nfe_proc"},
			{"v4_0/consulta_situacao", "v4_0/consulta_situacao"},
			{"v4_0/status_servico", "v4_0/status_servico"},
			{"v4_0/inutilizacao", "v4_0/inutilizacao"},
		},
		postprocess: postprocessNFe,
	}
}

func nfseFamily() family {
	return family{
		name: "nfse",
		xgenJobs: []xgenJob{
			{"v1_0/core", "v1_0/core"},
		},
		postprocess: postprocessNFSe,
	}
}

func postprocessBPe(verbose bool) error {
	return runGeneratedPostprocess(verbose, generatedPostprocessSpec{
		genDir: "internal/bpe/gen",
		nestedImportPatterns: []string{
			pathPattern("internal", "bpe", "schemas"),
			pathPattern("internal", "bpe", "gen", "v1_0", "schemas"),
		},
		workarounds: []generatedWorkaround{
			workaround("replace pointer interface fields with strings", postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("*interface{}"), "*string")),
			workaround("replace interface fields with strings", postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("interface{}"), "string")),
			workaround("fix typed root aliases from schema definitions", fixTypedRootAliasFromSchema),
			workaround("fix BPe Comp field type mismatch", postprocess.ReplaceAll(infBPeCompField, infBPeCompFieldFixed)),
			workaround("preserve raw detEvento payload XML for BPe event base types", postprocess.IfPath(
				func(path string) bool {
					return strings.HasSuffix(path, string(filepath.Separator)+"eventoBPeTiposBasico_v1.00.xsd.go")
				},
				postprocess.AddStructField(postprocess.TypeNamed("TAnonComplexDetEvento1"), "InnerXML", "string", `xml:",innerxml"`),
			)),
			workaround("flatten BPe event protocol wrappers to string values", postprocess.IfPath(
				func(path string) bool {
					return hasAnySuffix(path,
						string(filepath.Separator)+"evAlteracaoPoltrona_v1.00.xsd.go",
						string(filepath.Separator)+"evCancBPe_v1.00.xsd.go",
						string(filepath.Separator)+"evExcessoBagagem_v1.00.xsd.go",
						string(filepath.Separator)+"evNaoEmbBPe_v1.00.xsd.go",
					)
				},
				postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("NProt"), postprocess.FieldTypeEquals("*TProt")), "string"),
			)),
		},
		addJSONTags: true,
	})
}

func postprocessCTe(verbose bool) error {
	return runGeneratedPostprocess(verbose, generatedPostprocessSpec{
		genDir: "internal/cte/gen",
		nestedImportPatterns: []string{
			pathPattern("nfelib", "nfelib", "cte", "schemas"),
			pathPattern("internal", "cte", "schemas"),
			pathPattern("internal", "cte", "gen", "v4_0", "schemas"),
		},
		removeFile: func(path string) (bool, string) {
			return isDiscardedCTeModalSupportFile(path), "removed modal support schema package"
		},
		workarounds: []generatedWorkaround{
			workaround("replace CTe event payload placeholders with typed modal payloads", replaceTypedCTeEventPayloads),
			workaround("replace pointer interface fields with strings", postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("*interface{}"), "*string")),
			workaround("replace interface fields with strings", postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("interface{}"), "string")),
			workaround("fix typed root aliases from schema definitions", fixTypedRootAliasFromSchema),
			workaround("make DhCont optional in generated CTe structs", postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("DhCont"), postprocess.FieldTypeEquals("string")), "*string")),
			workaround("make XJust optional in generated CTe structs", postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("XJust"), postprocess.FieldTypeEquals("string")), "*string")),
			workaround("make CRT optional in generated CTe structs", postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("CRT"), postprocess.FieldTypeEquals("string")), "*string")),
			workaround("flatten selected CTe event protocol wrappers to string values", postprocess.IfPath(
				func(path string) bool {
					return hasAnySuffix(path,
						string(filepath.Separator)+"evCancCTe_v4.00.xsd.go",
						string(filepath.Separator)+"evCECTe_v4.00.xsd.go",
						string(filepath.Separator)+"evCancCECTe_v4.00.xsd.go",
						string(filepath.Separator)+"evCancIECTe_v4.00.xsd.go",
						string(filepath.Separator)+"evIECTe_v4.00.xsd.go",
					)
				},
				postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("NProt"), postprocess.FieldTypeEquals("*TProt")), "string"),
			)),
			workaround("flatten CTe disagreement event protocol wrapper to string value", postprocess.IfPath(
				func(path string) bool {
					return strings.HasSuffix(path, string(filepath.Separator)+"evCancPrestDesacordo_v4.00.xsd.go")
				},
				postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("NProtEvPrestDes"), postprocess.FieldTypeEquals("*TProt")), "string"),
			)),
		},
		addJSONTags: true,
	})
}

func postprocessMDFe(verbose bool) error {
	return runGeneratedPostprocess(verbose, generatedPostprocessSpec{
		genDir: "internal/mdfe/gen",
		nestedImportPatterns: []string{
			pathPattern("nfelib", "nfelib", "mdfe", "schemas"),
			pathPattern("internal", "mdfe", "schemas"),
			pathPattern("internal", "mdfe", "gen", "v3_0", "schemas"),
		},
		workarounds: []generatedWorkaround{
			workaround("replace MDFe ambient enum pointers with strings", postprocess.ReplaceAll("*TpAmb", "*string")),
			workaround("fix typed root aliases from schema definitions", fixTypedRootAliasFromSchema),
			workaround("preserve raw infModal payload XML in MDFe root type", postprocess.AddStructField(postprocess.TypeNamed("InfModal"), "InnerXML", "string", `xml:",innerxml"`)),
			workaround("preserve raw infModal payload XML in MDFe anonymous type", postprocess.AddStructField(postprocess.TypeNamed("TAnonComplexInfModal1"), "InnerXML", "string", `xml:",innerxml"`)),
			workaround("flatten selected MDFe event protocol wrappers to string values", postprocess.IfPath(
				func(path string) bool {
					return hasAnySuffix(path,
						string(filepath.Separator)+"evAlteracaoPagtoServMDFe_v3.00.xsd.go",
						string(filepath.Separator)+"evCancMDFe_v3.00.xsd.go",
						string(filepath.Separator)+"evConfirmaServMDFe_v3.00.xsd.go",
						string(filepath.Separator)+"evEncMDFe_v3.00.xsd.go",
						string(filepath.Separator)+"evInclusaoDFeMDFe_v3.00.xsd.go",
						string(filepath.Separator)+"evPagtoOperMDFe_v3.00.xsd.go",
					)
				},
				postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("NProt"), postprocess.FieldTypeEquals("*TProt")), "string"),
			)),
			workaround("preserve raw detEvento payload XML for MDFe event base types", postprocess.IfPath(
				func(path string) bool {
					return strings.HasSuffix(path, string(filepath.Separator)+"eventoMDFeTiposBasico_v3.00.xsd.go")
				},
				postprocess.AddStructField(postprocess.TypeNamed("DetEvento", "TAnonComplexDetEvento1"), "InnerXML", "string", `xml:",innerxml"`),
			)),
		},
		addJSONTags: true,
	})
}

func postprocessNFe(verbose bool) error {
	return runGeneratedPostprocess(verbose, generatedPostprocessSpec{
		genDir: "internal/nfe/gen",
		nestedImportPatterns: []string{
			pathPattern("internal", "nfe", "schemas"),
			pathPattern("internal", "nfe", "gen", "v1_0", "schemas"),
			pathPattern("internal", "nfe", "gen", "v4_0", "schemas"),
		},
		removeFile: func(path string) (bool, string) {
			return isDuplicateGeneratedNFeFragment(path), "removed duplicated imported schema package"
		},
		workarounds: []generatedWorkaround{
			workaround("replace pointer interface fields with strings", postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("*interface{}"), "*string")),
			workaround("replace interface fields with strings", postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("interface{}"), "string")),
			workaround("fix typed root aliases from schema definitions", fixTypedRootAliasFromSchema),
			workaround("flatten NFe cancel event protocol wrapper to string value", postprocess.IfPath(
				func(path string) bool {
					return strings.HasSuffix(path, string(filepath.Separator)+"leiauteEventoCancNFe_v1.00.xsd.go")
				},
				postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("NProt"), postprocess.FieldTypeEquals("*TProt")), "string"),
			)),
			workaround("replace unsupported NFe evento_cce enums with strings", postprocess.IfPath(
				postprocess.PathContains("internal", "nfe", "gen", "v1_0", "evento_cce"),
				postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("*TCOrgaoIBGE"), "*string"),
				postprocess.ReplaceFieldType(postprocess.FieldTypeEquals("*TVerEvento"), "*string"),
			)),
		},
		addJSONTags: true,
	})
}

func postprocessNFSe(verbose bool) error {
	return runGeneratedPostprocess(verbose, generatedPostprocessSpec{
		genDir: "internal/nfse/gen",
		nestedImportPatterns: []string{
			pathPattern("nfelib", "nfelib", "nfse", "schemas"),
			pathPattern("internal", "nfse", "schemas"),
			pathPattern("internal", "nfse", "gen", "v1_0", "schemas"),
		},
		workarounds: []generatedWorkaround{
			workaround("fix typed root aliases from schema definitions", fixTypedRootAliasFromSchema),
			workaround("replace NFSe xDesc interface payload with string", postprocess.ReplaceFieldType(postprocess.AllFields(postprocess.FieldNamed("XDesc"), postprocess.FieldTypeEquals("interface{}")), "string")),
		},
		addJSONTags: true,
	})
}

func replaceTypedCTeEventPayloads(path, updated string) string {
	if strings.HasSuffix(path, string(filepath.Separator)+"cteTiposBasico_v4.00.xsd.go") && usesTypedCTeInfModal(path) {
		spec, ok := cteInfModalSpecFor(path)
		if !ok {
			return updated
		}

		updated = postprocess.EnsureNamedImports(spec.imports)(path, updated)
		updated = postprocess.SetStructFields(postprocess.AnyType(
			postprocess.TypeNamed("InfModal"),
			postprocess.TypeNamed("TAnonComplexInfModal1"),
			postprocess.TypeNamed("TAnonComplexInfModal2"),
			postprocess.TypeNamed("TAnonComplexInfModal3"),
		), spec.fields)(path, updated)
	}
	if strings.HasSuffix(path, string(filepath.Separator)+"eventoCTeTiposBasico_v4.00.xsd.go") {
		for folder, element := range cteEventPayloads {
			if strings.Contains(path, string(filepath.Separator)+folder+string(filepath.Separator)) {
				updated = postprocess.SetStructFields(postprocess.AnyType(
					postprocess.TypeNamed("DetEvento"),
					postprocess.TypeNamed("TAnonComplexDetEvento1"),
				), cteDetEventoFields(element))(path, updated)
				break
			}
		}
	}
	return updated
}

type cteInfModalSpec struct {
	imports map[string]string
	fields  []postprocess.StructFieldSpec
}

func fixTypedRootAliasFromSchema(path, updated string) string {
	match := rootAliasFile.FindStringSubmatch(updated)
	if len(match) != 2 {
		return updated
	}

	schemaPath, ok := schemaPathForGenerated(path)
	if !ok {
		return updated
	}

	schemaText, err := os.ReadFile(schemaPath)
	if err != nil {
		return updated
	}

	rootType, ok := schemaRootTypeFromSchema(schemaText)
	if !ok {
		return updated
	}

	return postprocess.SetTypeExpr(postprocess.TypeNamed(match[1]), "*"+rootType)(path, updated)
}

func schemaRootTypeFromSchema(schemaText []byte) (string, bool) {
	decoder := xml.NewDecoder(bytes.NewReader(schemaText))
	for {
		tok, err := decoder.Token()
		if err != nil {
			if errors.Is(err, io.EOF) {
				return "", false
			}
			return "", false
		}

		start, ok := tok.(xml.StartElement)
		if !ok || start.Name.Local != "element" {
			continue
		}

		name := xmlAttrValue(start.Attr, "name")
		typeName := xmlAttrValue(start.Attr, "type")
		if name == "" || typeName == "" {
			continue
		}
		return typeName, true
	}
}

func xmlAttrValue(attrs []xml.Attr, name string) string {
	for _, attr := range attrs {
		if attr.Name.Local == name {
			return attr.Value
		}
	}
	return ""
}

func schemaPathForGenerated(path string) (string, bool) {
	clean := filepath.Clean(path)
	needle := string(filepath.Separator) + "gen" + string(filepath.Separator)
	idx := strings.Index(clean, needle)
	if idx == -1 {
		return "", false
	}

	schemaPath := clean[:idx] + string(filepath.Separator) + "schemas" + string(filepath.Separator) + clean[idx+len(needle):]
	schemaPath = strings.TrimSuffix(schemaPath, ".go")
	if _, err := os.Stat(schemaPath); err != nil {
		return "", false
	}
	return schemaPath, true
}

func isDiscardedCTeModalSupportFile(path string) bool {
	if filepath.Base(filepath.Dir(path)) == "v4_0" && strings.HasPrefix(filepath.Base(path), "modal_") {
		return true
	}

	parent := filepath.Base(filepath.Dir(path))
	allowed := map[string]string{
		"modal_aereo":         "cteModalAereo_v4.00.xsd.go",
		"modal_aquaviario":    "cteModalAquaviario_v4.00.xsd.go",
		"modal_dutoviario":    "cteModalDutoviario_v4.00.xsd.go",
		"modal_ferroviario":   "cteModalFerroviario_v4.00.xsd.go",
		"modal_rodoviario":    "cteModalRodoviario_v4.00.xsd.go",
		"modal_rodoviario_os": "cteModalRodoviarioOS_v4.00.xsd.go",
		"modal_multimodal":    "cteMultiModal_v4.00.xsd.go",
	}

	rootFile, ok := allowed[parent]
	if !ok {
		return false
	}
	return filepath.Base(path) != rootFile
}

func usesTypedCTeInfModal(path string) bool {
	parent := filepath.Base(filepath.Dir(path))
	for _, folder := range []string{"cte", "cte_os", "cte_simp", "gtve"} {
		if parent == folder {
			return true
		}
	}
	return false
}

func cteInfModalImports(osOnly bool) map[string]string {
	if osOnly {
		return map[string]string{
			"modalrodoviarioos": "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_rodoviario_os",
		}
	}
	return map[string]string{
		"modalaereo":       "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_aereo",
		"modalaquaviario":  "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_aquaviario",
		"modaldutoviario":  "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_dutoviario",
		"modalferroviario": "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_ferroviario",
		"modalmultimodal":  "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_multimodal",
		"modalrodoviario":  "github.com/awafinance/fiscal/internal/cte/gen/v4_0/modal_rodoviario",
	}
}

func cteInfModalFields(osOnly bool) []postprocess.StructFieldSpec {
	fields := []postprocess.StructFieldSpec{
		{Name: "XMLName", Type: "xml.Name", Tag: `xml:"infModal"`},
		{Name: "VersaoModalAttr", Type: "string", Tag: `xml:"versaoModal,attr"`},
	}
	if osOnly {
		return append(fields, postprocess.StructFieldSpec{
			Name: "RodoOS", Type: "modalrodoviarioos.RodoOS", Tag: `xml:"rodoOS,omitempty"`,
		})
	}
	return append(fields,
		postprocess.StructFieldSpec{Name: "Rodo", Type: "modalrodoviario.Rodo", Tag: `xml:"rodo,omitempty"`},
		postprocess.StructFieldSpec{Name: "Aereo", Type: "modalaereo.Aereo", Tag: `xml:"aereo,omitempty"`},
		postprocess.StructFieldSpec{Name: "Aquav", Type: "modalaquaviario.Aquav", Tag: `xml:"aquav,omitempty"`},
		postprocess.StructFieldSpec{Name: "Ferrov", Type: "modalferroviario.Ferrov", Tag: `xml:"ferrov,omitempty"`},
		postprocess.StructFieldSpec{Name: "Duto", Type: "modaldutoviario.Duto", Tag: `xml:"duto,omitempty"`},
		postprocess.StructFieldSpec{Name: "Multimodal", Type: "modalmultimodal.Multimodal", Tag: `xml:"multimodal,omitempty"`},
	)
}

func cteInfModalSpecFor(path string) (cteInfModalSpec, bool) {
	if strings.Contains(path, string(filepath.Separator)+"cte_os"+string(filepath.Separator)) {
		return cteInfModalSpec{
			imports: cteInfModalImports(true),
			fields:  cteInfModalFields(true),
		}, true
	}

	return cteInfModalSpec{
		imports: cteInfModalImports(false),
		fields:  cteInfModalFields(false),
	}, true
}

func cteDetEventoFields(element string) []postprocess.StructFieldSpec {
	typeSuffix := strings.ToUpper(element[:1]) + element[1:]
	return []postprocess.StructFieldSpec{
		{Name: "XMLName", Type: "xml.Name", Tag: `xml:"detEvento"`},
		{Name: "VersaoEventoAttr", Type: "string", Tag: `xml:"versaoEvento,attr"`},
		{Name: typeSuffix, Type: fmt.Sprintf("*TAnonComplex%s1", typeSuffix), Tag: fmt.Sprintf(`xml:"%s"`, element)},
	}
}

func isDuplicateGeneratedNFeFragment(path string) bool {
	clean := filepath.Clean(path)
	base := filepath.Base(clean)

	switch {
	case strings.Contains(clean, pathPattern("internal", "nfe", "gen", "v1_0", "ator_interessado")):
		return base == "110150_v1.00.xsd.go"
	case strings.Contains(clean, pathPattern("internal", "nfe", "gen", "v1_0", "evento_mde")):
		return base == "e210200_v1.00.xsd.go" ||
			base == "e210210_v1.00.xsd.go" ||
			base == "e210220_v1.00.xsd.go" ||
			base == "e210240_v1.00.xsd.go"
	case strings.Contains(clean, pathPattern("internal", "nfe", "gen", "v1_0", "evento_insucesso")):
		return base == "tmp0000.xsd.go"
	}

	return false
}

func pathPattern(elem ...string) string {
	return string(filepath.Separator) + filepath.Join(elem...) + string(filepath.Separator)
}

func hasAnySuffix(path string, suffixes ...string) bool {
	for _, suffix := range suffixes {
		if strings.HasSuffix(path, suffix) {
			return true
		}
	}
	return false
}
